function WriteOrder(basedir, stimorder, f, name)
%stim.WriteOrder(basedir, stimorder)
%writes a stimorder file for binoc into basedir.
%stimorder can be a vector of stimulus id numbers, setting the order
%OR a two element vector(nstim, nrpts), in whcih case teh order is
%generated by Write order. N.B to use this, the stim files must exist
%and be numbered 0:nstim-1
%stim.WriteOrder(basedir, stimorder, exptvars, name, stimorder)
filename = [basedir '/stimorder'];
fid = fopen(filename,'w');
if fid < 0
    cprintf('red','Cannot Write to file %s\n',filename);
    return;
end

if length(stimorder) ==2 && max(stimorder) > 2
    nstim = stimorder(1);
    nrpts = stimorder(2);
    stimorder = repmat([0:nstim-1],1,nrpts);
    stimorder = stimorder(randperm(length(stimorder)));
end

if nargin > 2
    fprintf(fid,'expvars=%s',f{1});
    for j = 2:length(f)
        fprintf(fid,',%s',f{j});
    end
    fprintf(fid,'\n');
end
if nargin > 3
    if ischar(name)
        fprintf(fid,'expname=%s\n',name);
    elseif isfield(name,'expname')
        fprintf(fid,'expname=%s\n',name.expname);
    end
    if isfield(name,'filename') %saved details of matlab stimuli
        fprintf(fid,'expfilename=%s\n',name.filename);
    end
end
fprintf(fid,'%s\n',sprintf('%d ',stimorder));
fclose(fid);
